<a href="https://colab.research.google.com/github/silapareddypraveen/silapareddypraveen/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([200,2,222,11])
print(a)

[200   2 222  11]


In [ ]:
list=[1000,2222,5996]
b=np.array(list)
print(b)

[1000 2222 5996]


In [ ]:
c=np.arange(1,30,1)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


2 dimentional array

In [ ]:
a=np.array([[22,55,56],[22,44,55]])
b=np.array([[33,55,66],[666,888,999]])
c=np.array([[55,88,99],[447,55,88]])
d=np.array([[66,8,8],[333,555,666]])
print(a)
print(b[1][2])
print(c[1][0])
print(d[0][0])

[[22 55 56]
 [22 44 55]]
999
447
66


3d


In [ ]:
b=np.array([[[33,44,55,554],[333,6665,555,6666]],[[45,56,67,78],[666,888,999,9997]]])
print(b[1][0][0])
print(b)

45
[[[  33   44   55  554]
  [ 333 6665  555 6666]]

 [[  45   56   67   78]
  [ 666  888  999 9997]]]


In [ ]:
a=[[200,300],[400,500]]
b=np.asarray(a,order="f")
print(b)
for i in np.nditer(b):
       print(i)

[[200 300]
 [400 500]]
200
400
300
500


In [ ]:
a=b"FIRST YEAR  OF CSE STUDENTS"
np.frombuffer(a,dtype="S1")

array([b'F', b'I', b'R', b'S', b'T', b' ', b'Y', b'E', b'A', b'R', b' ',
       b' ', b'O', b'F', b' ', b'C', b'S', b'E', b' ', b'S', b'T', b'U',
       b'D', b'E', b'N', b'T', b'S'], dtype='|S1')

In [ ]:
a=np.zeros(166)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = np.zeros([2,3,3],dtype=int)
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
a=np.full([4,4],6)
print(a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
a=np.random.rand(2,2)
print(a)

[[0.84025974 0.80262336]
 [0.33823416 0.29101333]]


In [ ]:
a=np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
a=np.arange(1,22,5)
print(a)

[ 1  6 11 16 21]


In [ ]:
a=np.arange(30,50,2)
print(a)
a.reshape(5,2)
a.reshape(1,10)

[30 32 34 36 38 40 42 44 46 48]


array([[30, 32, 34, 36, 38, 40, 42, 44, 46, 48]])

In [ ]:
a=np.linspace(10,100,10,dtype=int)
print(a)